image: gitpod/workspace-full-vnc

tasks:
- name: SETUP - MAMBA ENVIRONMENT
  init: |
    wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh

    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n verkko -c conda-forge -c bioconda -c defaults verkko bedtools -y
    sudo apt install -y fuse

    cd /workspace
    # get data and utility scripts
    curl -L https://obj.umiacs.umd.edu/training/bga2024_verkko_t2t_data.tar.gz | tar xzf -
    git clone https://github.com/marbl/training.git
    mv training/part2-assemble/docker/marbl_utils /workspace/marbl_utils && rm -rf ./training
    
    # get bandageNG
    wget https://github.com/asl/BandageNG/releases/download/continuous/BandageNG-Linux-8dd0544.AppImage
    mv BandageNG-Linux-8dd0544.AppImage BandageNG
    chmod u+x BandageNG
    
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba activate verkko
    export PATH=/workspace/mambaforge/envs/verkko/bin/:$PATH
    
    cd /workspace
    clear

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
