image: gitpod/workspace-full-vnc

tasks:
- name: SETUP - MAMBA ENVIRONMENT
  init: |
    cd /workspace
    wget "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/mambaforge && rm Mambaforge-$(uname)-$(uname -m).sh

    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n verkko -c conda-forge -c bioconda -c defaults verkko -y

command: |
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba activate verkko

    cd /workspace
    clear

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
